---
- hosts: web
  tasks:
    - name: Installing Apache
      yum:
        state: present
        name: 
          - httpd
          - mariadb-server
          - php
          - php-mysql
          - MySQL-python
    - name: Services starting
      service:
        state: started
        name: httpd
        enabled: true

    - name: Services starting
      service:
        state: started
        name: mariadb
        enabled: true
    - name: 3. Create a new database
      mysql_db: name=demo state=present collation=utf8_general_ci

    - name: 4. Create a database user
      mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present
    - name: 4. install Hello World PHP script
      copy: src=index.php dest=/var/www/html/index.php mode=0664
    - name: 5a. Copy sample data
      copy: src=dump.sql dest=/tmp/dump.sql
    - name: 7. install Hello World PHP script with database
      copy: src=db.php dest=/var/www/html/db.php mode=0664
    - name: 5b. Insert sample data
      shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo
    - name: 6b. Restart Apache
      service: name=httpd state=restarted
